version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: simple-php-mvc
    container_name: simple-php-pvc
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - simple-php-mvc

  db:
    image: mysql:8.0
    container_name: simple-php-mvc-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - simple-php-mvc

  nginx:
    image: nginx:alpine
    container_name: simple-php-mvc-nginx
    restart: unless-stopped
    ports:
      - 2024:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - simple-php-mvc

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: simple-php-mvc-phpmyadmin
    links:
      - db
    environment:
        PMA_HOST: db
        PMA_PORT: 3306
    ports:
        - 8081:80
    networks:
        - simple-php-mvc

networks:
  simple-php-mvc:
    driver: bridge
